# front.yml
apiVersion: v1
kind: Service
metadata:
  name: front
spec:
  selector:
    app: front
  ports:
  - port: 3000
    targetPort: 80
    name: front
    protocol: TCP
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
spec:
  selector:
    matchLabels:
      app: front
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: REPO/IMAGE:TAG
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: front
        