export const GET_MY_PROFILE_REQUEST = 'GET_MY_PROFILE_REQUEST';
export const GET_MY_PROFILE_SUCCESS = 'GET_MY_PROFILE_SUCCESS';
export const GET_MY_PROFILE_FAILURE = 'GET_MY_PROFILE_FAILURE';
export const GET_MY_DAILY_REQUEST = 'GET_MY_DAILY_REQUEST';
export const GET_MY_DAILY_SUCCESS = 'GET_MY_DAILY_SUCCESS';
export const GET_MY_DAILY_FAILURE = 'GET_MY_DAILY_FAILURE';
